<?php

/**
 * This is the model base class for the table "ahorro_deposito".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AhorroDeposito".
 *
 * Columns in table "ahorro_deposito" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $cantidad
 * @property integer $entidad_bancaria_id
 * @property string $cod_comprobante_entidad
 * @property string $fecha_comprobante_entidad
 * @property integer $sucursal_comprobante_id
 * @property string $cod_comprobante_su
 * @property string $fecha_comprobante_su
 * @property integer $usuario_creacion_id
 *
 */
abstract class BaseAhorroDeposito extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ahorro_deposito';
    }

    public static function representingColumn() {
        return 'cantidad';
    }

    public function rules() {
        return array(
            array('cantidad, entidad_bancaria_id, cod_comprobante_entidad, fecha_comprobante_entidad, sucursal_comprobante_id, cod_comprobante_su, fecha_comprobante_su, usuario_creacion_id', 'required'),
            array('entidad_bancaria_id, sucursal_comprobante_id, usuario_creacion_id', 'numerical', 'integerOnly'=>true),
            array('cantidad', 'length', 'max'=>10),
            array('cod_comprobante_entidad, cod_comprobante_su', 'length', 'max'=>45),
            array('id, cantidad, entidad_bancaria_id, cod_comprobante_entidad, fecha_comprobante_entidad, sucursal_comprobante_id, cod_comprobante_su, fecha_comprobante_su, usuario_creacion_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'entidad_bancaria_id' => Yii::t('app', 'Entidad Bancaria'),
                'cod_comprobante_entidad' => Yii::t('app', 'Cod Comprobante Entidad'),
                'fecha_comprobante_entidad' => Yii::t('app', 'Fecha Comprobante Entidad'),
                'sucursal_comprobante_id' => Yii::t('app', 'Sucursal Comprobante'),
                'cod_comprobante_su' => Yii::t('app', 'Cod Comprobante Su'),
                'fecha_comprobante_su' => Yii::t('app', 'Fecha Comprobante Su'),
                'usuario_creacion_id' => Yii::t('app', 'Usuario Creacion'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('cantidad', $this->cantidad, true);
        $criteria->compare('entidad_bancaria_id', $this->entidad_bancaria_id);
        $criteria->compare('cod_comprobante_entidad', $this->cod_comprobante_entidad, true);
        $criteria->compare('fecha_comprobante_entidad', $this->fecha_comprobante_entidad, true);
        $criteria->compare('sucursal_comprobante_id', $this->sucursal_comprobante_id);
        $criteria->compare('cod_comprobante_su', $this->cod_comprobante_su, true);
        $criteria->compare('fecha_comprobante_su', $this->fecha_comprobante_su, true);
        $criteria->compare('usuario_creacion_id', $this->usuario_creacion_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}