<?php

/**
 * This is the model base class for the table "ahorro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ahorro".
 *
 * Columns in table "ahorro" available as properties of the model,
 * followed by relations of table "ahorro" available as properties of the model.
 *
 * @property integer $id
 * @property string $descripcion
 * @property integer $socio_id
 * @property string $cantidad
 * @property string $fecha
 * @property string $estado
 * @property string $tipo
 * @property string $saldo_contra
 * @property string $saldo_favor
 * @property string $saldo_extra
 * @property integer $anulado
 *
 * @property AhorroDeposito[] $ahorroDepositos
 */
abstract class BaseAhorro extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ahorro';
    }

    public static function representingColumn() {
        return 'descripcion';
    }

    public function rules() {
        return array(
            array('descripcion, socio_id, cantidad, fecha, tipo', 'required'),
            array('socio_id, anulado', 'numerical', 'integerOnly'=>true),
            array('descripcion', 'length', 'max'=>50),
            array('cantidad, saldo_contra, saldo_favor', 'length', 'max'=>10),
            array('estado', 'length', 'max'=>6),
            array('tipo', 'length', 'max'=>11),
            array('estado', 'in', 'range' => array('DEUDA','PAGADO')), // enum,
            array('tipo', 'in', 'range' => array('OBLIGATORIO','VOLUNTARIO','PRIMER_PAGO')), // enum,
            array('saldo_contra, saldo_favor, anulado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, descripcion, socio_id, cantidad, fecha, estado, tipo, saldo_contra, saldo_favor, anulado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ahorroDepositos' => array(self::HAS_MANY, 'AhorroDeposito', 'pago_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'socio_id' => Yii::t('app', 'Socio'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'fecha' => Yii::t('app', 'Fecha'),
                'estado' => Yii::t('app', 'Estado'),
                'tipo' => Yii::t('app', 'Tipo'),
                'saldo_contra' => Yii::t('app', 'Saldo Contra'),
                'saldo_favor' => Yii::t('app', 'Saldo Favor'),
                //'saldo_extra' => Yii::t('app', 'Saldo Extra'),
                'anulado' => Yii::t('app', 'Anulado'),
                'ahorroDepositos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('socio_id', $this->socio_id);
        $criteria->compare('cantidad', $this->cantidad, true);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('saldo_contra', $this->saldo_contra, true);
        $criteria->compare('saldo_favor', $this->saldo_favor, true);
        //$criteria->compare('saldo_extra', $this->saldo_extra, true);
        $criteria->compare('anulado', $this->anulado);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}