<?php

/**
 * This is the model base class for the table "direccion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Direccion".
 *
 * Columns in table "direccion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $calle_1
 * @property string $calle_2
 * @property string $numero
 * @property string $referencia
 * @property string $tipo
 * @property integer $barrio_id
 * @property integer $parroquia_id
 *
 */
abstract class BaseDireccion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'direccion';
    }

    public static function representingColumn() {
        return 'tipo';
    }

    public function rules() {
        return array(
            array('tipo, parroquia_id', 'required'),
            array('barrio_id, parroquia_id', 'numerical', 'integerOnly'=>true),
            array('calle_1, calle_2', 'length', 'max'=>128),
            array('numero', 'length', 'max'=>8),
            array('tipo', 'length', 'max'=>1),
            array('referencia', 'safe'),
            array('tipo', 'in', 'range' => array('C','S','E')), // enum,
            array('calle_1, calle_2, numero, referencia, barrio_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, calle_1, calle_2, numero, referencia, tipo, barrio_id, parroquia_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'calle_1' => Yii::t('app', 'Calle 1'),
                'calle_2' => Yii::t('app', 'Calle 2'),
                'numero' => Yii::t('app', 'Numero'),
                'referencia' => Yii::t('app', 'Referencia'),
                'tipo' => Yii::t('app', 'Tipo'),
                'barrio_id' => Yii::t('app', 'Barrio'),
                'parroquia_id' => Yii::t('app', 'Parroquia'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('calle_1', $this->calle_1, true);
        $criteria->compare('calle_2', $this->calle_2, true);
        $criteria->compare('numero', $this->numero, true);
        $criteria->compare('referencia', $this->referencia, true);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('barrio_id', $this->barrio_id);
        $criteria->compare('parroquia_id', $this->parroquia_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}