<?php

/**
 * This is the model base class for the table "parroquia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Parroquia".
 *
 * Columns in table "parroquia" available as properties of the model,
 * followed by relations of table "parroquia" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $canton_id
 *
 * @property Barrio[] $barrios
 * @property Direccion[] $direccions
 * @property Canton $canton
 */
abstract class BaseParroquia extends AweActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'parroquia';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, canton_id', 'required'),
            array('canton_id', 'numerical', 'integerOnly' => true),
            array('nombre', 'length', 'max' => 32),
            array('id, nombre, canton_id', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'barrios' => array(self::HAS_MANY, 'Barrio', 'parroquia_id'),
            'direccions' => array(self::HAS_MANY, 'Direccion', 'parroquia_id'),
            'canton' => array(self::BELONGS_TO, 'Canton', 'canton_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'nombre' => Yii::t('app', 'Nombre'),
            'canton_id' => Yii::t('app', 'Canton'),
            'barrios' => null,
            'direccions' => null,
            'canton' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('canton_id', $this->canton_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
                ), parent::behaviors());
    }

}
