<?php

/**
 * This is the model base class for the table "ahorro_retiro_detalle".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AhorroRetiroDetalle".
 *
 * Columns in table "ahorro_retiro_detalle" available as properties of the model,
 * followed by relations of table "ahorro_retiro_detalle" available as properties of the model.
 *
 * @property integer $id
 * @property string $cantidad
 * @property integer $ahorro_id
 * @property integer $ahorro_retiro_id
 *
 * @property AhorroRetiro $ahorroRetiro
 */
abstract class BaseAhorroRetiroDetalle extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ahorro_retiro_detalle';
    }

    public static function representingColumn() {
        return 'cantidad';
    }

    public function rules() {
        return array(
            array('cantidad, ahorro_id, ahorro_retiro_id', 'required'),
            array('ahorro_id, ahorro_retiro_id', 'numerical', 'integerOnly'=>true),
            array('cantidad', 'length', 'max'=>10),
            array('id, cantidad, ahorro_id, ahorro_retiro_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ahorroRetiro' => array(self::BELONGS_TO, 'AhorroRetiro', 'ahorro_retiro_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'ahorro_id' => Yii::t('app', 'Ahorro'),
                'ahorro_retiro_id' => Yii::t('app', 'Ahorro Retiro'),
                'ahorroRetiro' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('cantidad', $this->cantidad, true);
        $criteria->compare('ahorro_id', $this->ahorro_id);
        $criteria->compare('ahorro_retiro_id', $this->ahorro_retiro_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}