<?php

/**
 * This is the model base class for the table "ahorro_retiro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AhorroRetiro".
 *
 * Columns in table "ahorro_retiro" available as properties of the model,
 * followed by relations of table "ahorro_retiro" available as properties of the model.
 *
 * @property integer $id
 * @property integer $socio_id
 * @property integer $sucursal_id
 * @property string $cantidad
 * @property string $fecha_retiro
 * @property string $comprobante_retiro
 * @property integer $entidad_bancaria_id
 * @property integer $usuario_creacion_id
 *
 * @property AhorroRetiroDetalle[] $ahorroRetiroDetalles
 */
abstract class BaseAhorroRetiro extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ahorro_retiro';
    }

    public static function representingColumn() {
        return 'cantidad';
    }

    public function rules() {
        return array(
            array('socio_id, sucursal_id, cantidad, fecha_retiro, comprobante_retiro, entidad_bancaria_id, usuario_creacion_id', 'required'),
            array('socio_id, sucursal_id, entidad_bancaria_id, usuario_creacion_id', 'numerical', 'integerOnly'=>true),
            array('cantidad', 'length', 'max'=>10),
            array('comprobante_retiro', 'length', 'max'=>45),
            array('id, socio_id, sucursal_id, cantidad, fecha_retiro, comprobante_retiro, entidad_bancaria_id, usuario_creacion_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ahorroRetiroDetalles' => array(self::HAS_MANY, 'AhorroRetiroDetalle', 'ahorro_retiro_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'socio_id' => Yii::t('app', 'Socio'),
                'sucursal_id' => Yii::t('app', 'Sucursal'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'fecha_retiro' => Yii::t('app', 'Fecha Retiro'),
                'comprobante_retiro' => Yii::t('app', 'Comprobante Retiro'),
                'entidad_bancaria_id' => Yii::t('app', 'Entidad Bancaria'),
                'usuario_creacion_id' => Yii::t('app', 'Usuario Creacion'),
                'ahorroRetiroDetalles' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('socio_id', $this->socio_id);
        $criteria->compare('sucursal_id', $this->sucursal_id);
        $criteria->compare('cantidad', $this->cantidad, true);
        $criteria->compare('fecha_retiro', $this->fecha_retiro, true);
        $criteria->compare('comprobante_retiro', $this->comprobante_retiro, true);
        $criteria->compare('entidad_bancaria_id', $this->entidad_bancaria_id);
        $criteria->compare('usuario_creacion_id', $this->usuario_creacion_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}