<?php

/**
 * This is the model base class for the table "credito_devolucion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CreditoDevolucion".
 *
 * Columns in table "credito_devolucion" available as properties of the model,
 * followed by relations of table "credito_devolucion" available as properties of the model.
 *
 * @property integer $id
 * @property string $cantidad
 * @property string $estado
 * @property integer $usuario_devolucion_id
 * @property string $fecha_devolucion
 * @property integer $credito_deposito_id
 *
 * @property CreditoDeposito $creditoDeposito
 */
abstract class BaseCreditoDevolucion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'credito_devolucion';
    }

    public static function representingColumn() {
        return 'cantidad';
    }

    public function rules() {
        return array(
            array('cantidad, estado, credito_deposito_id', 'required'),
            array('usuario_devolucion_id, credito_deposito_id', 'numerical', 'integerOnly'=>true),
            array('cantidad', 'length', 'max'=>10),
            array('estado', 'length', 'max'=>11),
            array('fecha_devolucion', 'safe'),
            array('estado', 'in', 'range' => array('NO DEVUELTO','DEVUELTO')), // enum,
            array('usuario_devolucion_id, fecha_devolucion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, cantidad, estado, usuario_devolucion_id, fecha_devolucion, credito_deposito_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'creditoDeposito' => array(self::BELONGS_TO, 'CreditoDeposito', 'credito_deposito_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'estado' => Yii::t('app', 'Estado'),
                'usuario_devolucion_id' => Yii::t('app', 'Usuario Devolucion'),
                'fecha_devolucion' => Yii::t('app', 'Fecha Devolucion'),
                'credito_deposito_id' => Yii::t('app', 'Credito Deposito'),
                'creditoDeposito' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('cantidad', $this->cantidad, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('usuario_devolucion_id', $this->usuario_devolucion_id);
        $criteria->compare('fecha_devolucion', $this->fecha_devolucion, true);
        $criteria->compare('credito_deposito_id', $this->credito_deposito_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}