<?php

/**
 * This is the model base class for the table "sucursal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sucursal".
 *
 * Columns in table "sucursal" available as properties of the model,
 * followed by relations of table "sucursal" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $direccion_id
 * @property string $estado
 * @property double $valor_inscripcion
 * @property double $valor_ahorro
 *
 * @property Persona[] $personas
 * @property Direccion $direccion
 */
abstract class BaseSucursal extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'sucursal';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, direccion_id, estado, valor_inscripcion, valor_ahorro', 'required'),
            array('direccion_id', 'numerical', 'integerOnly'=>true),
            array('valor_inscripcion, valor_ahorro', 'numerical'),
            array('nombre', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>8),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('id, nombre, direccion_id, estado, valor_inscripcion, valor_ahorro', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'personas' => array(self::HAS_MANY, 'Persona', 'sucursal_id'),
            'direccion' => array(self::BELONGS_TO, 'Direccion', 'direccion_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'direccion_id' => Yii::t('app', 'Direccion'),
                'estado' => Yii::t('app', 'Estado'),
                'valor_inscripcion' => Yii::t('app', 'Valor Inscripcion'),
                'valor_ahorro' => Yii::t('app', 'Valor Ahorro'),
                'personas' => null,
                'direccion' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('direccion_id', $this->direccion_id);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('valor_inscripcion', $this->valor_inscripcion);
        $criteria->compare('valor_ahorro', $this->valor_ahorro);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}