<?php

/**
 * This is the model base class for the table "actividad_economica".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActividadEconomica".
 *
 * Columns in table "actividad_economica" available as properties of the model,
 * followed by relations of table "actividad_economica" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $estado
 *
 * @property Persona[] $personas
 */
abstract class BaseActividadEconomica extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'actividad_economica';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre', 'length', 'max'=>50),
            array('estado', 'length', 'max'=>8),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('nombre, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'personas' => array(self::HAS_MANY, 'Persona', 'actividad_economica_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'estado' => Yii::t('app', 'Estado'),
                'personas' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('estado', $this->estado, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}