<?php

/**
 * This is the model base class for the table "deposito".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Deposito".
 *
 * Columns in table "deposito" available as properties of the model,
 * followed by relations of table "deposito" available as properties of the model.
 *
 * @property integer $id
 * @property string $cantidad
 * @property integer $entidad_bancaria_id
 * @property string $cod_comprobante_entidad
 * @property string $fecha_comprobante_entidad
 * @property integer $sucursal_comprobante_id
 * @property string $cod_comprobante_su
 * @property string $fecha_comprobante_su
 * @property integer $pago_id
 *
 * @property Pago $pago
 */
abstract class BaseDeposito extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'deposito';
    }

    public static function representingColumn() {
        return 'cantidad';
    }

    public function rules() {
        return array(
            array('cantidad, entidad_bancaria_id, pago_id', 'required'),
            array('entidad_bancaria_id, sucursal_comprobante_id, pago_id', 'numerical', 'integerOnly'=>true),
            array('cantidad, cod_comprobante_entidad, cod_comprobante_su', 'length', 'max'=>45),
            array('fecha_comprobante_entidad, fecha_comprobante_su', 'safe'),
            array('cod_comprobante_entidad, fecha_comprobante_entidad, sucursal_comprobante_id, cod_comprobante_su, fecha_comprobante_su', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, cantidad, entidad_bancaria_id, cod_comprobante_entidad, fecha_comprobante_entidad, sucursal_comprobante_id, cod_comprobante_su, fecha_comprobante_su, pago_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'pago' => array(self::BELONGS_TO, 'Pago', 'pago_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'cantidad' => Yii::t('app', 'Cantidad'),
                'entidad_bancaria_id' => Yii::t('app', 'Entidad Bancaria'),
                'cod_comprobante_entidad' => Yii::t('app', 'Codigo Comprobante Entidad'),
                'fecha_comprobante_entidad' => Yii::t('app', 'Fecha Comprobante Entidad'),
                'sucursal_comprobante_id' => Yii::t('app', 'Sucursal'),
                'cod_comprobante_su' => Yii::t('app', 'Codigo Comprobante Sucursal'),
                'fecha_comprobante_su' => Yii::t('app', 'Fecha Comprobante Sucursal'),
                'pago_id' => Yii::t('app', 'Pago'),
                'pago' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('cantidad', $this->cantidad, true);
        $criteria->compare('entidad_bancaria_id', $this->entidad_bancaria_id);
        $criteria->compare('cod_comprobante_entidad', $this->cod_comprobante_entidad, true);
        $criteria->compare('fecha_comprobante_entidad', $this->fecha_comprobante_entidad, true);
        $criteria->compare('sucursal_comprobante_id', $this->sucursal_comprobante_id);
        $criteria->compare('cod_comprobante_su', $this->cod_comprobante_su, true);
        $criteria->compare('fecha_comprobante_su', $this->fecha_comprobante_su, true);
        $criteria->compare('pago_id', $this->pago_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}